---
name: Continuous Deployment

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build image
      run: docker build -t ${GITHUB_REPOSITORY}:${GITHUB_SHA::8} -t ${GITHUB_REPOSITORY}:latest .

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Push to Docker Hub
      run: docker push ${GITHUB_REPOSITORY}
