---
name: Continuous Integration

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get Composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Attempt to get Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install --optimize-autoloader

      - name: Run PHPUnit tests
        run: composer run-script test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build .
